In [1]:
%env CUDA_DEVICE_ORDER=PCI_BUS_ID
%env CUDA_VISIBLE_DEVICES=5

env: CUDA_DEVICE_ORDER=PCI_BUS_ID
env: CUDA_VISIBLE_DEVICES=5

In [2]:
import pandas as pd
import csv

In [3]:
# Define the lang code
lang_code = "ES-CT"

# Define final path
final_path = "/home/tajak/Parlamint-translation/Note-translation/Final-data-CSV/ParlaMint-{}.notes.translated.ana.tsv".format(lang_code)

temp_path = "/home/tajak/Parlamint-translation/Note-translation/Final-data-CSV/before-sorting/ParlaMint-{}.notes.translated-before-sorting.ana.csv".format(lang_code)

In [4]:
# Open the dataframe
df = pd.read_csv(final_path, sep="\t")

df.head(2)

,tag,type,content,xml:lang,length,translation,corpus
0,gap,inaudible,"Per raons tècniques, no han quedat enregistrat...",ca,15,"For technical reasons, the first words of the ...",ES-CT
1,gap,inaudible,L'oradora comença a parlar sense fer ús del mi...,ca,19,The speaker began to speak without using the m...,ES-CT

## Analyse results

In [5]:
df.describe(include="all")

,tag,type,content,xml:lang,length,translation,corpus
count,42026,36774,42026,42026,42026.000000,42026,42026
unique,5,15,41838,9,NaN,41070,1
top,vocal,interruption,Varga Zoltán: Ez nem igaz!,hu,NaN,Dr. Varga-Damm Andrea:,HU
freq,31818,30318,2,41989,NaN,37,42026
mean,NaN,NaN,NaN,NaN,7.765550,NaN,NaN
std,NaN,NaN,NaN,NaN,4.992851,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,7.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,9.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,191.000000,NaN,NaN

In [6]:
# Print total no. of words
df.length.sum()

221203

In [7]:
df.head(20)

,tag,type,content,xml:lang,length,translation,corpus
0,gap,editorial,The frontmatter of the document has been removed,en,8,The frontmatter of the document has been remov...,GR
1,head,NaN,ΠΡΑΚΤΙΚΑ ΒΟΥΛΗΣ,el,2,PRACTICAL STUDIES,GR
2,head,NaN,ΠΡΟΕΔΡΕΥΟΜΕΝΗΣ ΚΟΙΝΟΒΟΥΛΕΥΤΙΚΗΣ ΔΗΜΟΚΡΑΤΙΑΣ,el,3,PRE-FILLED PARLIAMENT REPUBLIC,GR
3,head,date,Παρασκευή 5 Μαΐου 2017,el,4,Friday 5 May 2017,GR
4,head,date,Δευτέρα 4 Δεκεμβρίου 2017,el,4,Monday 4 December 2017,GR
5,head,date,Δευτέρα 20 Νοεμβρίου 2017,el,4,Monday 20 November 2017,GR
6,head,date,Πέμπτη 20 Απριλίου 2017,el,4,Thursday 20 April 2017,GR
7,head,date,Τετάρτη 2 Αυγούστου 2017,el,4,Wednesday 2 August 2017,GR
8,head,date,Πέμπτη 26 Οκτωβρίου 2017,el,4,Thursday 26 October 2017,GR
9,head,date,Παρασκευή 7 Απριλίου 2017,el,4,Friday 7 April 2017,GR
10,head,date,Δευτέρα 11 Σεπτεμβρίου 2017,el,4,Monday 11 September 2017,GR
11,head,date,Δευτέρα 24 Ιουλίου 2017,el,4,Monday 24 July 2017,GR
12,head,date,Τετάρτη 8 Νοεμβρίου 2017 (πρωί),el,5,Wednesday 8 November 2017 (morning),GR
13,head,date,Παρασκευή 8 Σεπτεμβρίου 2017,el,4,Friday 8 September 2017,GR
14,head,date,Πέμπτη 29 Ιουνίου 2017,el,4,Thursday 29 June 2017,GR
15,head,date,Τρίτη 7 Φεβρουαρίου 2017,el,4,Tuesday 7 February 2017,GR
16,head,date,Δευτέρα 4 Σεπτεμβρίου 2017,el,4,Monday 4 September 2017,GR
17,head,date,Τετάρτη 7 Ιουνίου 2017,el,4,Wednesday 7 June 2017,GR
18,head,date,Δευτέρα 27 Νοεμβρίου 2017,el,4,Monday 27 November 2017,GR
19,head,date,Δευτέρα 22 Μαΐου 2017,el,4,Monday 22 May 2017,GR

## Remove foreign language

In [5]:
# Inspect whether there is any additional language
print(df.shape)
print(df["xml:lang"].value_counts().to_markdown())

(11603, 7)
|    |   xml:lang |
|:---|-----------:|
| ca |      11229 |
| es |        374 |

In [17]:
df[df["xml:lang"] == "en"]

,tag,type,content,xml:lang,length,translation,corpus
0,gap,editorial,Technical problem: content could not be proces...,en,11,Technical problem: content would not be proces...,FI

In [18]:
# Remove instances that are in non-target language
df = df[df["xml:lang"] == "fi"]

# Inspect the results
df.describe(include="all")

,tag,type,content,xml:lang,length,translation,corpus
count,8503,5087,8503,8503,8503.000000,8503,8503
unique,2,1,8503,1,NaN,8485,1
top,note,relatedDocument,Hallituksen esitys eduskunnalle laeiksi euroop...,fi,NaN,Government proposal HE 9/2015 vp,FI
freq,5087,5087,1,8503,NaN,3,8503
mean,NaN,NaN,NaN,NaN,6.940492,NaN,NaN
std,NaN,NaN,NaN,NaN,4.366581,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,7.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,51.000000,NaN,NaN

In [20]:
df.length.sum()

59015

In [21]:
df.to_csv("{}".format(final_path), index=False, sep="\t", quoting=csv.QUOTE_NONE, quotechar="",  escapechar="\\")

After saving, inspect the saved file - check whether quotes are still present (that you did not delete them by saving the file too many times.)