In [1]:
%env CUDA_DEVICE_ORDER=PCI_BUS_ID
%env CUDA_VISIBLE_DEVICES=2

env: CUDA_DEVICE_ORDER=PCI_BUS_ID
env: CUDA_VISIBLE_DEVICES=2

In [2]:
import pandas as pd
import csv

In [3]:
# Define the lang code
lang_code = "ES-CT"

# Define final path
final_path = "/home/tajak/Parlamint-translation/Note-translation/Final-data-CSV/ParlaMint-{}.notes.translated.tsv".format(lang_code)

In [4]:
# Open the dataframe
df = pd.read_csv(final_path, sep="\t")
#df = pd.read_csv(final_path, sep="\t", engine='python', quoting=csv.QUOTE_NONE, quotechar="",  escapechar="\\")

df.head(2)

,tag,type,content,xml:lang,length,translation,corpus
0,gap,inaudible,"(Per raons tècniques, no han quedat enregistra...",ca,15,"(For technical reasons, the first words of the...",ES-CT
1,gap,inaudible,"(Per raons tècniques, no han quedat enregistra...",ca,15,"(For technical reasons, the first words of the...",ES-CT

In [12]:
import csv
# Save the file again, without quote escaping
df.to_csv("/home/tajak/Parlamint-translation/Note-translation/Final-data-CSV/ParlaMint-AT.notes.translated-quotes-escaped.tsv", index=False, sep="\t", quoting=csv.QUOTE_NONE, quotechar="",  escapechar="\\")

## Analyse results

In [10]:
df.describe(include="all")

,tag,type,content,xml:lang,length,translation,corpus
count,650031,637198,650030,650031,650031.000000,650030,650031
unique,2,2,649618,3,NaN,640591,1
top,note,comment,(Munterhet i salen),nb,NaN,(The vote will be taken at 5 p.m. (Parliament ...,NO
freq,637198,426659,3,649096,NaN,510,650031
mean,NaN,NaN,NaN,NaN,11.559529,NaN,NaN
std,NaN,NaN,NaN,NaN,14.660229,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,4.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,670.000000,NaN,NaN

In [6]:
# Print total no. of words
df.length.sum()

221203

In [7]:
df.head(20)

,tag,type,content,xml:lang,length,translation,corpus
0,gap,editorial,The frontmatter of the document has been removed,en,8,The frontmatter of the document has been remov...,GR
1,head,NaN,ΠΡΑΚΤΙΚΑ ΒΟΥΛΗΣ,el,2,PRACTICAL STUDIES,GR
2,head,NaN,ΠΡΟΕΔΡΕΥΟΜΕΝΗΣ ΚΟΙΝΟΒΟΥΛΕΥΤΙΚΗΣ ΔΗΜΟΚΡΑΤΙΑΣ,el,3,PRE-FILLED PARLIAMENT REPUBLIC,GR
3,head,date,Παρασκευή 5 Μαΐου 2017,el,4,Friday 5 May 2017,GR
4,head,date,Δευτέρα 4 Δεκεμβρίου 2017,el,4,Monday 4 December 2017,GR
5,head,date,Δευτέρα 20 Νοεμβρίου 2017,el,4,Monday 20 November 2017,GR
6,head,date,Πέμπτη 20 Απριλίου 2017,el,4,Thursday 20 April 2017,GR
7,head,date,Τετάρτη 2 Αυγούστου 2017,el,4,Wednesday 2 August 2017,GR
8,head,date,Πέμπτη 26 Οκτωβρίου 2017,el,4,Thursday 26 October 2017,GR
9,head,date,Παρασκευή 7 Απριλίου 2017,el,4,Friday 7 April 2017,GR
10,head,date,Δευτέρα 11 Σεπτεμβρίου 2017,el,4,Monday 11 September 2017,GR
11,head,date,Δευτέρα 24 Ιουλίου 2017,el,4,Monday 24 July 2017,GR
12,head,date,Τετάρτη 8 Νοεμβρίου 2017 (πρωί),el,5,Wednesday 8 November 2017 (morning),GR
13,head,date,Παρασκευή 8 Σεπτεμβρίου 2017,el,4,Friday 8 September 2017,GR
14,head,date,Πέμπτη 29 Ιουνίου 2017,el,4,Thursday 29 June 2017,GR
15,head,date,Τρίτη 7 Φεβρουαρίου 2017,el,4,Tuesday 7 February 2017,GR
16,head,date,Δευτέρα 4 Σεπτεμβρίου 2017,el,4,Monday 4 September 2017,GR
17,head,date,Τετάρτη 7 Ιουνίου 2017,el,4,Wednesday 7 June 2017,GR
18,head,date,Δευτέρα 27 Νοεμβρίου 2017,el,4,Monday 27 November 2017,GR
19,head,date,Δευτέρα 22 Μαΐου 2017,el,4,Monday 22 May 2017,GR

## Remove foreign language

In [9]:
# Inspect whether there is any additional language
print(df.shape)
df["xml:lang"].value_counts()

(11997, 7)

ca    11650
es      347
Name: xml:lang, dtype: int64

In [6]:
df[df["xml:lang"] == "en"]

,tag,type,content,xml:lang,length,translation,corpus
11921,vocal,murmuring,(Veus de fons.),en,3,(Founding wishes.),ES-CT

In [10]:
# Remove instances that are in non-target language
df = df[df["xml:lang"] == "el"]

# Inspect the results
df.describe(include="all")

,tag,type,content,xml:lang,length,translation,corpus
count,11750,3485,11750,11750,11750.000000,11750,11750
unique,5,10,11750,1,NaN,11115,1
top,note,date,ΠΡΑΚΤΙΚΑ ΒΟΥΛΗΣ,el,NaN,IN THE CHAIR: MRS PERY Vice-President,GR
freq,9169,1259,1,11750,NaN,37,11750
mean,NaN,NaN,NaN,NaN,18.825106,NaN,NaN
std,NaN,NaN,NaN,NaN,18.515140,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,31.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,686.000000,NaN,NaN

In [11]:
df.length.sum()

221195

In [14]:
df.to_csv("{}".format(final_path), index=False, sep="\t", quoting=csv.QUOTE_NONE, quotechar="",  escapechar="\\")